import React, { useMemo, useState } from "react";
import { Calculator as CalculatorIcon } from "lucide-react";
import { PageHeader, Card, Field, Input } from "../components/ui";
import { inr } from "../lib/format";

const n = (v) => Math.max(0, Number(v) || 0);
const payment = (p, r, months) => r ? p * r * Math.pow(1 + r, months) / (Math.pow(1 + r, months) - 1) : p / Math.max(months, 1);
export default function Calculators() {
  const [loan,setLoan]=useState({balance:500000,rate:9,months:60,extra:5000}), [goal,setGoal]=useState({target:1000000,saved:200000,months:60,rate:10}), [reserve,setReserve]=useState({expense:50000,months:6,saved:100000}), [retire,setRetire]=useState({monthly:60000,years:25,inflation:6,returnRate:10,current:300000}), [rental,setRental]=useState({price:5000000,rent:25000,annualCost:50000,loan:2500000,rate:9}), [step,setStep]=useState({target:1500000,current:100000,monthly:10000,step:10,years:10,rate:10}), [recovery,setRecovery]=useState({principal:120000,recovered:20000,monthly:8000,months:12});
  const lr=useMemo(()=>{const r=n(loan.rate)/1200, emi=payment(n(loan.balance),r,n(loan.months)), total=emi+n(loan.extra), finish=r&&total>r*n(loan.balance)?Math.ceil(Math.log(total/(total-r*n(loan.balance)))/Math.log(1+r)):n(loan.months); return {emi,saved:Math.max(0,n(loan.months)-finish)}},[loan]);
  const goalR=useMemo(()=>{const r=n(goal.rate)/1200, remain=Math.max(0,n(goal.target)-n(goal.saved)); return r?remain*r/(Math.pow(1+r,n(goal.months))-1):remain/Math.max(n(goal.months),1)},[goal]);
  const retireR=useMemo(()=>{const y=n(retire.years), spend=n(retire.monthly)*Math.pow(1+n(retire.inflation)/100,y), corpus=spend*12*25, months=y*12,r=n(retire.returnRate)/1200,future=n(retire.current)*Math.pow(1+r,months); return {spend,corpus,monthly:Math.max(0,r?(corpus-future)*r/(Math.pow(1+r,months)-1):(corpus-future)/Math.max(months,1))}},[retire]);
  const rentalR=useMemo(()=>{const annual=n(rental.rent)*12,net=annual-n(rental.annualCost);return {gross:n(rental.price)?annual/n(rental.price)*100:0,net:n(rental.price)?net/n(rental.price)*100:0,annual:net}},[rental]);
  const sip=useMemo(()=>{let v=n(step.current), monthly=n(step.monthly),r=n(step.rate)/1200;for(let i=0;i<n(step.years)*12;i++){v=(v+monthly)*(1+r);if((i+1)%12===0)monthly*=1+n(step.step)/100}return {v,gap:Math.max(0,n(step.target)-v)}},[step]);
  const rec=useMemo(()=>{const out=Math.max(0,n(recovery.principal)-n(recovery.recovered)), expected=Math.min(out,n(recovery.monthly)*n(recovery.months));return {out,expected,gap:Math.max(0,out-expected)}},[recovery]);
  return <><PageHeader title="Planning Calculators" subtitle="Practical household estimates for decisions—not investment advice or return promises." icon={CalculatorIcon}/><div className="grid xl:grid-cols-3 gap-6"><Calc title="Loan prepayment"><Fields d={loan} s={setLoan} f={[["balance","Outstanding balance"],["rate","Interest % p.a."],["months","Remaining months"],["extra","Extra monthly payment"]]}/><Result l="Estimated EMI" v={inr(lr.emi)}/><Result l="Finish sooner by" v={`${lr.saved} months`}/></Calc><Calc title="Goal / SIP planner"><Fields d={goal} s={setGoal} f={[["target","Goal amount"],["saved","Already saved"],["months","Months to target"],["rate","Expected return % p.a."]]}/><Result l="Required monthly contribution" v={inr(goalR)}/></Calc><Calc title="Emergency reserve"><Fields d={reserve} s={setReserve} f={[["expense","Monthly essential expenses"],["months","Target reserve months"],["saved","Available emergency savings"]]}/><Result l="Remaining reserve to build" v={inr(Math.max(0,n(reserve.expense)*n(reserve.months)-n(reserve.saved)))}/><Result l="Target reserve" v={inr(n(reserve.expense)*n(reserve.months))}/></Calc><Calc title="Retirement corpus"><Fields d={retire} s={setRetire} f={[["monthly","Current monthly spending"],["years","Years until retirement"],["inflation","Inflation % p.a."],["returnRate","Expected return % p.a."],["current","Current retirement savings"]]}/><Result l="Monthly spend at retirement" v={inr(retireR.spend)}/><Result l="Illustrative corpus (25 years)" v={inr(retireR.corpus)}/><Result l="Monthly saving estimate" v={inr(retireR.monthly)}/></Calc><Calc title="Rental yield"><Fields d={rental} s={setRental} f={[["price","Property value"],["rent","Monthly rent"],["annualCost","Annual maintenance / tax"],["loan","Loan outstanding"],["rate","Loan interest % p.a."]]}/><Result l="Gross rental yield" v={`${rentalR.gross.toFixed(2)}%`}/><Result l="Net rental yield" v={`${rentalR.net.toFixed(2)}%`}/><Result l="Net rent before EMI" v={inr(rentalR.annual)}/></Calc><Calc title="SIP step-up"><Fields d={step} s={setStep} f={[["target","Target amount"],["current","Current corpus"],["monthly","Starting monthly SIP"],["step","Annual SIP step-up %"],["years","Years"],["rate","Expected return % p.a."]]}/><Result l="Projected value" v={inr(sip.v)}/><Result l="Gap to target" v={inr(sip.gap)}/></Calc><Calc title="Lending recovery"><Fields d={recovery} s={setRecovery} f={[["principal","Original amount lent"],["recovered","Already recovered"],["monthly","Expected monthly recovery"],["months","Recovery plan months"]]}/><Result l="Outstanding" v={inr(rec.out)}/><Result l="Expected recovery" v={inr(rec.expected)}/><Result l="Plan gap" v={inr(rec.gap)}/></Calc></div></>;
}
function Calc({title,children}){return <Card className="p-5"><h2 className="font-display font-semibold text-ink">{title}</h2><div className="space-y-3 mt-4">{children}</div></Card>}; function Fields({d,s,f}){return f.map(([k,l])=><Field key={k} label={l}><Input type="number" min="0" step="any" value={d[k]} onChange={e=>s({...d,[k]:e.target.value})}/></Field>)}; function Result({l,v}){return <div className="flex justify-between gap-3 border-t border-line pt-3 text-sm"><span className="text-subink">{l}</span><span className="num font-bold text-ink text-right">{v}</span></div>}
