import React, { useEffect, useState } from "react";
import { BookOpen, LockKeyhole, Plus, Trash2, ShieldCheck } from "lucide-react";
import { PageHeader, Card, Button, Modal, Field, Input, Textarea, StateBlock } from "../components/ui";
import api, { apiError } from "../lib/api";
import { todayISO } from "../lib/format";

export default function Diary() {
  const [token, setToken] = useState(() => sessionStorage.getItem("nivara_losses_token") || "");
  const headers = { "X-Loss-Token": token };
  const [rows, setRows] = useState([]); const [loading, setLoading] = useState(!!token); const [error, setError] = useState(""); const [open, setOpen] = useState(false); const [form, setForm] = useState({ date: todayISO() }); const [password, setPassword] = useState("");
  const load = () => { if (!token) return; setLoading(true); api.get("/diary", { headers }).then((r) => setRows(r.data)).catch((e) => setError(apiError(e))).finally(() => setLoading(false)); };
  useEffect(() => { load(); /* eslint-disable-next-line */ }, [token]);
  const save = async () => { if (!form.body) { setError("Write something before saving."); return; } try { await api.post("/diary", form, { headers }); setOpen(false); setForm({ date: todayISO() }); load(); } catch (e) { setError(apiError(e)); } };
  const remove = async (row) => { if (!window.confirm("Delete this diary entry?")) return; await api.delete(`/diary/${row.id}`, { headers }); load(); };
  const unlock = async () => { try { const r = await api.post("/losses/unlock", { password }); sessionStorage.setItem("nivara_losses_token", r.data.token); setToken(r.data.token); setPassword(""); } catch (e) { setError(apiError(e)); } };
  if (!token) return <><PageHeader title="Daily Diary" subtitle="Private notes, protected by the admin lock." icon={BookOpen} /><Modal open={true} onClose={() => window.history.back()} title="Unlock Daily Diary"><div className="text-center"><LockKeyhole className="mx-auto text-amber mb-3" /><p className="text-sm text-subink mb-4">Enter the admin password to write or read private diary entries.</p><Field label="Admin password"><Input autoFocus type="password" value={password} onChange={(e) => setPassword(e.target.value)} onKeyDown={(e) => e.key === "Enter" && unlock()} /></Field>{error && <p className="text-sm text-expense mt-2">{error}</p>}<Button className="w-full mt-4" onClick={unlock}><ShieldCheck size={15} /> Unlock diary</Button></div></Modal></>;
  return <><PageHeader title="Daily Diary" subtitle="Private daily reflections and personal notes." icon={BookOpen} actions={<Button size="sm" onClick={() => setOpen(true)}><Plus size={15} /> Write entry</Button>} /><StateBlock loading={loading} error={error} onRetry={load} empty={!rows.length} emptyText="No diary entries yet."><div className="space-y-3">{rows.map((row) => <Card className="p-5" key={row.id}><div className="flex justify-between gap-3"><div><div className="overline text-faint">{row.date}</div><h3 className="font-display font-semibold text-ink mt-1">{row.title || "Daily note"}</h3></div><button onClick={() => remove(row)} className="text-faint hover:text-expense"><Trash2 size={16} /></button></div><p className="text-sm text-subink whitespace-pre-wrap mt-3">{row.body}</p></Card>)}</div></StateBlock><Modal open={open} onClose={() => setOpen(false)} title="Write daily entry"><Field label="Date (YYYY-MM-DD)"><Input type="date" value={form.date} onChange={(e) => setForm({ ...form, date: e.target.value })} /></Field><Field label="Title" className="mt-3"><Input value={form.title || ""} onChange={(e) => setForm({ ...form, title: e.target.value })} placeholder="A small title" /></Field><Field label="Your entry" className="mt-3"><Textarea value={form.body || ""} onChange={(e) => setForm({ ...form, body: e.target.value })} className="min-h-[180px]" /></Field><div className="flex gap-2 pt-4"><Button variant="secondary" className="flex-1" onClick={() => setOpen(false)}>Cancel</Button><Button className="flex-1" onClick={save}>Save entry</Button></div></Modal></>;
}
