import React, { useState } from "react";
import { BellRing, Check, Plus, RefreshCw } from "lucide-react";
import { useFetch } from "../lib/useFetch";
import { PageHeader, StateBlock, Card, Badge, Button, Modal, Field, Input, Textarea, Select } from "../components/ui";
import api, { apiError } from "../lib/api";
import { inr, fmtDate } from "../lib/format";

const tone = { critical: "red", warning: "amber", info: "blue" };
export default function Notifications() {
  const [view, setView] = useState("OPEN"), [compose, setCompose] = useState(false), [form, setForm] = useState({ severity: "info" }), [err, setErr] = useState("");
  const { data, loading, error, refetch } = useFetch(`/notifications?status=${view}`);
  const items = Array.isArray(data?.items) ? data.items : [];
  const acknowledge = async (id) => { try { await api.post(`/notifications/${id}/acknowledge`); window.dispatchEvent(new Event("nivara:notifications-changed")); refetch(); } catch (e) { setErr(apiError(e)); } };
  const save = async (e) => { e.preventDefault(); try { await api.post("/notifications/reminders", form); setCompose(false); setForm({ severity: "info" }); refetch(); } catch (x) { setErr(apiError(x)); } };
  return <><PageHeader title="Notification center" subtitle="Every important money date, collection and overdue balance—tracked in one place." icon={BellRing} actions={<div className="flex gap-2"><Button variant="secondary" size="sm" onClick={refetch}><RefreshCw size={14}/> Refresh</Button><Button size="sm" onClick={() => setCompose(true)}><Plus size={15}/> Reminder</Button></div>} />
    <div className="flex gap-2 mb-5"><Button size="sm" variant={view === "OPEN" ? "primary" : "secondary"} onClick={() => setView("OPEN")}>Open</Button><Button size="sm" variant={view === "ALL" ? "primary" : "secondary"} onClick={() => setView("ALL")}>History</Button></div>
    {err && <p className="mb-4 text-sm text-expense">{err}</p>}<StateBlock loading={loading} error={error} empty={!items.length} emptyText="No notifications in this view." onRetry={refetch}>{<div className="grid gap-3">{items.map((item) => <Card key={item.id} className="p-4 sm:p-5"><div className="flex gap-3 justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold text-ink">{item.title}</h2><Badge tone={tone[item.severity] || "gray"}>{item.severity}</Badge><Badge>{item.kind.replaceAll("_", " ").toLowerCase()}</Badge></div><p className="text-sm text-subink mt-1">{item.message}</p><p className="text-xs text-faint mt-2">{item.due_date ? `Due ${fmtDate(item.due_date)}` : "No due date"}{item.acknowledged_at ? ` · acknowledged ${fmtDate(item.acknowledged_at)}` : ""}</p></div>{item.amount > 0 && <span className="num font-bold text-expense whitespace-nowrap">{inr(item.amount)}</span>}</div>{item.status === "OPEN" && <Button size="sm" variant="secondary" className="mt-4" onClick={() => acknowledge(item.id)}><Check size={14}/> Acknowledge</Button>}</Card>)}</div>}</StateBlock>
    <Modal open={compose} onClose={() => setCompose(false)} title="Create reminder"><form onSubmit={save} className="space-y-4"><Field label="Reminder title"><Input required value={form.title || ""} onChange={e => setForm({...form, title:e.target.value})} placeholder="Add PPF contribution" /></Field><Field label="Due date"><Input required type="date" value={form.due_date || ""} onChange={e => setForm({...form, due_date:e.target.value})}/></Field><Field label="Amount (optional)"><Input type="number" value={form.amount || ""} onChange={e => setForm({...form, amount:e.target.value})}/></Field><Field label="Priority"><Select value={form.severity} onChange={e => setForm({...form, severity:e.target.value})}><option value="info">Info</option><option value="warning">Needs attention</option><option value="critical">Critical</option></Select></Field><Field label="Note"><Textarea value={form.message || ""} onChange={e => setForm({...form, message:e.target.value})}/></Field><Button type="submit" className="w-full">Save reminder</Button></form></Modal></>;
}
