import React, { useMemo, useState } from "react";
import { ArrowUpRight, ChevronRight, CircleDollarSign, Landmark, Wallet, PieChart as PieIcon, Sparkles } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { useFetch } from "../lib/useFetch";
import { Badge, Card, DetailDrawer, Segmented, StateBlock } from "../components/ui";
import { Bars, ChartCard, Donut, TrendLine } from "../components/charts";
import { inr } from "../lib/format";
import ActionCenter from "../components/ActionCenter";

const ranges = [{ value: "1M", label: "1M" }, { value: "6M", label: "6M" }, { value: "1Y", label: "1Y" }, { value: "ALL", label: "All" }];

export default function Overview() {
  const nav = useNavigate(); const [range, setRange] = useState("ALL"), [drawer, setDrawer] = useState(null);
  const overview = useFetch("/dashboard/overview"), history = useFetch("/networth/history");
  const data = overview.data;
  const historyData = useMemo(() => { const all = history.data?.items || []; if (range === "ALL") return all; const days = range === "1M" ? 31 : range === "6M" ? 183 : 365; const after = new Date(Date.now() - days * 86400000).toISOString().slice(0, 10); return all.filter((point) => point.date >= after); }, [history.data, range]);
  return <StateBlock loading={overview.loading || history.loading} error={overview.error || history.error} onRetry={() => { overview.refetch(); history.refetch(); }}>
    {data && <div className="space-y-4 sm:space-y-5">
      <section className="grid xl:grid-cols-12 gap-4 sm:gap-5">
        <div className="xl:col-span-8 rounded-2xl bg-[#102b2b] text-white p-5 sm:p-7 min-h-[350px] flex flex-col overflow-hidden relative"><div className="absolute right-0 top-0 h-full w-1/2 opacity-20 bg-[radial-gradient(circle_at_top_right,_#5eead4,_transparent_62%)]"/><div className="relative flex flex-wrap items-start justify-between gap-4"><div><div className="overline text-teal-200">Total net worth</div><div className="num text-4xl sm:text-5xl font-bold tracking-tight mt-2">{inr(data.net_worth, { compact: true })}</div><div className="flex items-center gap-2 mt-3 text-sm text-teal-100"><span className={data.month_savings >= 0 ? "text-emerald-300" : "text-rose-300"}>{data.month_savings >= 0 ? "+" : ""}{inr(data.month_savings, { compact: true })}</span><span>this month’s net cash flow</span></div></div><Segmented options={ranges} value={range} onChange={setRange}/></div><div className="relative flex-1 min-h-[190px] mt-5">{historyData.length > 1 ? <TrendLine data={historyData} xKey="date" yKey="net_worth" name="Net worth" monthLabels={false} color="#5eead4"/> : <div className="h-full flex items-center justify-center text-sm text-teal-100/70">Your recorded valuation trend will build here over time.</div>}</div><div className="relative pt-3 border-t border-white/10 flex gap-5 text-xs text-teal-100"><button onClick={() => setDrawer("assets")} className="hover:text-white">Assets <strong className="num ml-1 text-white">{inr(data.total_assets, { compact: true })}</strong></button><button onClick={() => setDrawer("liabilities")} className="hover:text-white">Liabilities <strong className="num ml-1 text-white">{inr(data.total_liabilities, { compact: true })}</strong></button></div></div>
        <Card className="xl:col-span-4 p-5 sm:p-6 flex flex-col"><div className="flex items-center justify-between"><div><div className="overline text-faint">Financial position</div><h2 className="font-display font-semibold text-ink mt-1">Today at a glance</h2></div><span className="w-9 h-9 rounded-lg bg-teal-50 text-brand grid place-items-center"><Sparkles size={17}/></span></div><div className="divide-y divide-line mt-4">{[["Liquid today", data.cash_position?.available_now, Wallet, "/accounts"], ["Expected receivables", data.cash_position?.expected_receivables, CircleDollarSign, "/lending"], ["Known obligations", data.cash_position?.upcoming_obligations, Landmark, "/loans"]].map(([label, value, Icon, path]) => <button key={label} onClick={() => nav(path)} className="w-full flex items-center justify-between py-4 text-left group"><span className="flex items-center gap-3 text-sm text-subink"><Icon size={16} className="text-faint"/>{label}</span><span className="num font-bold text-ink group-hover:text-brand">{inr(value, { compact: true })}</span></button>)}</div><button onClick={() => nav("/planner")} className="mt-auto pt-4 text-sm text-brand font-semibold inline-flex items-center gap-1">Open financial planner <ArrowUpRight size={15}/></button></Card>
      </section>
      <section className="grid lg:grid-cols-12 gap-4 sm:gap-5"><ChartCard className="lg:col-span-4" title="Asset allocation" subtitle="Click to explore wealth" height={220}><Donut data={(data.allocation || []).filter((row) => row.value > 0)} centerLabel="Assets" centerValue={inr(data.total_assets, { compact: true })}/></ChartCard><ChartCard className="lg:col-span-4" title="Liability mix" subtitle="Outstanding obligations" height={220}>{data.liability_allocation?.some((row) => row.value > 0) ? <Donut data={data.liability_allocation.filter((row) => row.value > 0)} centerLabel="Owed" centerValue={inr(data.total_liabilities, { compact: true })}/> : <Empty label="No liabilities recorded"/>}</ChartCard><Card className="lg:col-span-4 p-5"><div className="flex items-center justify-between"><div><div className="overline text-faint">This month</div><h3 className="font-display font-semibold text-ink mt-1">What changed?</h3></div><button onClick={() => nav("/cash-flow")} className="text-brand"><ChevronRight size={18}/></button></div><div className="mt-5 space-y-3">{[["Income", data.month_income, "text-emerald-700"], ["Expenses", -data.month_expense, "text-rose-700"], ["Net cash flow", data.month_savings, "text-ink"]].map(([label, value, tone]) => <div key={label} className="flex justify-between text-sm"><span className="text-subink">{label}</span><span className={`num font-bold ${tone}`}>{value >= 0 ? "+" : ""}{inr(value, { compact: true })}</span></div>)}</div><div className="mt-5 pt-4 border-t border-line text-xs text-faint">Net-worth attribution will expand as valuations and investment activity accrue.</div></Card></section>
      <section className="grid lg:grid-cols-12 gap-4 sm:gap-5"><ChartCard className="lg:col-span-7" title="Cash flow" subtitle="Income and outflow by month" height={255}><Bars data={data.cash_flow || []} xKey="month" monthLabels series={[{ key:"in", name:"Income", color:"#0f766e" }, { key:"out", name:"Expenses", color:"#e11d48" }]}/></ChartCard><div className="lg:col-span-5"><ActionCenter compact/></div></section>
      <section className="grid md:grid-cols-3 gap-3"><Metric label="Investments" value={data.investments} onClick={() => nav("/savings")}/><Metric label="Money lent" value={data.lending_outstanding} onClick={() => nav("/lending")}/><Metric label="Review data" value="Open inbox" text onClick={() => nav("/review")}/></section>
      <DetailDrawer open={!!drawer} onClose={() => setDrawer(null)} title={drawer === "assets" ? "Asset allocation" : "Liabilities"} eyebrow="Financial breakdown"><div className="space-y-3">{(drawer === "assets" ? data.allocation : data.liability_allocation).filter((row) => row.value > 0).map((row) => <button onClick={() => nav(drawer === "assets" ? "/net-worth" : "/loans")} key={row.name} className="w-full text-left p-4 rounded-xl border border-line hover:border-teal-200 hover:bg-teal-50/40 flex justify-between"><span className="font-semibold text-ink">{row.name}</span><span className="num font-bold">{inr(row.value)}</span></button>)}</div></DetailDrawer>
    </div>}
  </StateBlock>;
}
function Empty({ label }) { return <div className="h-full grid place-items-center text-sm text-faint">{label}</div>; }
function Metric({ label, value, onClick, text }) { return <button onClick={onClick} className="text-left p-4 rounded-xl border border-line bg-white hover:border-teal-200 hover:shadow-xs transition"><div className="overline text-faint">{label}</div><div className="num text-xl font-bold text-ink mt-2">{text ? value : inr(value, { compact: true })}</div></button>; }
