import React, { useRef, useState } from "react";
import { Bot, CheckCircle2, FileUp, ShieldCheck } from "lucide-react";
import { Badge, Button, Card, Field, PageHeader, Select } from "../components/ui";
import api, { apiError } from "../lib/api";
import { inr } from "../lib/format";

export default function SmartImport() {
  const input = useRef();
  const [review, setReview] = useState(null), [busy, setBusy] = useState(false), [error, setError] = useState(""), [owner, setOwner] = useState("Self"), [selected, setSelected] = useState(new Set());
  const analyze = async (file) => { if (!file) return; setBusy(true); setError(""); try { const body = new FormData(); body.append("file", file); const { data } = await api.post("/imports/analyze", body, { headers: { "Content-Type": "multipart/form-data" } }); if (data.status === "ALREADY_IMPORTED") { setError(data.message); return; } setReview(data); setSelected(new Set(data.candidates.filter((row) => row.kind !== "NEEDS_GUIDANCE" && !row.duplicate).map((row) => row.row_number))); } catch (e) { setError(apiError(e)); } finally { setBusy(false); } };
  const commit = async () => { setBusy(true); setError(""); try { const { data } = await api.post(`/imports/${review.run_id}/commit`, { row_numbers: [...selected], owner }); setReview({ ...review, committed: data.summary }); } catch (e) { setError(apiError(e)); } finally { setBusy(false); } };
  const toggle = (row) => setSelected((current) => { const next = new Set(current); next.has(row) ? next.delete(row) : next.add(row); return next; });
  return <><PageHeader title="Import Center" subtitle="Analyze, review, reconcile and approve financial documents without silently changing your records." icon={Bot}/>
    <Card className="p-6 mb-6 bg-gradient-to-br from-teal-50 to-white"><div className="flex flex-col sm:flex-row gap-5 items-start sm:items-center justify-between"><div><h2 className="font-display font-bold text-ink">Bring a broker export into Nivara</h2><p className="text-sm text-subink mt-1">Every approved row retains its source document, row number, classifier confidence and duplicate fingerprint.</p></div><Button onClick={() => input.current?.click()} disabled={busy}><FileUp size={16}/>{busy ? "Analyzing…" : "Choose CSV or Excel"}</Button><input ref={input} className="hidden" type="file" accept=".csv,.xlsx,.xlsm" onChange={(event) => analyze(event.target.files?.[0])}/></div>{error && <p className="text-sm text-expense mt-4">{error}</p>}</Card>
    {review && <Card className="overflow-hidden"><div className="p-5 border-b border-line flex flex-wrap gap-4 justify-between"><div><div className="flex gap-2 items-center"><h2 className="font-display font-semibold text-ink">{review.provider} · {review.document_type}</h2><Badge tone="blue">{Math.round(review.document_confidence * 100)}% detected</Badge></div><p className="text-xs text-subink mt-1">{review.total_rows} rows · {review.filename} · duplicates are excluded by default.</p></div>{review.committed ? <Badge tone="green"><CheckCircle2 size={13}/> {review.committed.created + review.committed.consolidated} applied</Badge> : <div className="flex gap-2 items-end"><Field label="Owner"><Select value={owner} onChange={(event) => setOwner(event.target.value)}><option>Self</option><option>Family</option><option>Farm / business</option></Select></Field><Button onClick={commit} disabled={busy || !selected.size}><ShieldCheck size={15}/> Apply {selected.size} approved rows</Button></div>}</div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-muted/60 overline text-faint"><tr><th className="p-3 text-left">Apply</th><th className="p-3 text-left">Detected</th><th className="p-3 text-left">Record</th><th className="p-3 text-right">Value / P&L</th><th className="p-3 text-left">Reason</th></tr></thead><tbody>{review.candidates.map((row) => <tr key={row.row_number} className="border-t border-line"><td className="p-3"><input type="checkbox" disabled={!!review.committed || row.kind === "NEEDS_GUIDANCE" || row.duplicate} checked={selected.has(row.row_number)} onChange={() => toggle(row.row_number)}/></td><td className="p-3"><Badge tone={row.duplicate ? "amber" : row.kind === "NEEDS_GUIDANCE" ? "amber" : row.kind === "HISTORICAL_PNL" ? "blue" : "green"}>{row.duplicate ? "Duplicate" : row.kind.replace("_", " ")}</Badge></td><td className="p-3 font-medium text-ink">{row.name}</td><td className="p-3 text-right num">{inr(row.amount ?? row.current_value)}</td><td className="p-3 text-xs text-subink">{row.reason} · {Math.round(row.confidence * 100)}%</td></tr>)}</tbody></table></div></Card>}</>;
}
